### ISSUE TITLE
What happened to this repo?

### ISSUE THREAD

**Issue by muesli** [fclairamb/ftpserver#5]
Suddenly all the releases are gone? Has the repo been wiped and the code uploaded freshly?

**Comment by fclairamb** [comment]
Hi @muesli,

Your concerns are very valid. The existing repository has been renamed [ftpserverlib](https://github.com/fclairamb/ftpserverlib), and the release are [there](https://github.com/fclairamb/ftpserverlib/releases), I made a fork of this one here but I forgot to push the tags in this repository.

I'm changing a few things:
- The name was a bad one, it's a library and not an actual server. So I moved the upcoming library to [fclairamb/ftpserverlib](https://github.com/fclairamb/ftpserverlib)
- The sample implementation of the server was considered by many users like an actual server when it clearly wasn't. So I decided to make this repository an actual FTP Server that can be used by many people as-is. One of my first goal is to offer FTP to S3/Dropbox/Gdrive.
- I broke a lot of the existing APIs:
  - By splitting things more correctly between the sample server and the library, it allowed me to make quite some changes to the repository structure to make it cleaner (for example move the tests next to the code) but that breaks existing API.
  - I decided to update the file access API to use a more standard one ([afero](https://github.com/spf13/afero)) so that it's easier to integrate and so that building backends for it is more motivating. The actual changes were quite simple because both afero and my file implementation were very close to the Go types.
  - I decided to update the logging API to be more opinionated and allow to use other kinds of libraries (I have [uber/zap](https://github.com/uber/zap) in mind) and simplify the logging rules.

So:
- The server/library as you know it is about to disappear. But existing tags should still work now.
- The upcoming library should be a lot easier to integrate, you can basically just provide
- The upcoming server should be a lot more powerful. And I think in some cases people will be more interested in having a more generic configuration backend to the server than using the library.

I'm happy to help you to update your existing code to the library or get you up to date on the server.

**Comment by muesli** [comment]
Thanks for the detailed explanation @fclairamb! Greatly appreciated!

**Comment by fclairamb** [comment]
@muesli you're project is very interesting and even if the server definitely wasn't built for this kind of use-case, the upcoming version (still in PR #8) will.

I really like the intensive tests you added and the general choice of backends you took.

The funny thing is we are targeting the same kind of backends. On my end I decided to go with  [afero](https://github.com/spf13/afero) to handle all FS, it's a win/win in the sense of:
- It's easier for anyone to integrate a backend on this server
- Any implemented backend (like [the one I reworked for S3](https://github.com/fclairamb/afero-s3)) can be re-used for any other project
